name: CI — Docker build & tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t aceest-fitness:ci .

      - name: Run pytest inside the image
        # Override the image CMD so we run tests instead of starting Flask
        run: docker run --rm aceest-fitness:ci pytest -v
